spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

knife4j:
  enable: true

arcsoft:
  global:
    app-id: "BRMRGJvqKDTNRxaoeHQJoLLXp78PcPUMCBo3HMPcGbh3"
    sdk-key: "HXiqiJpzVGsbyJQuMaR9CUvBkwLPdtb4ux7NnrN2SWdz"
    sdk-lib-path: "E:\\webproject\\zsebank\\face\\face\\lib"


